name = "blockchain-worker"
main = "worker.js"
compatibility_date = "2023-09-04"

# 添加KV命名空间来存储区块链数据
kv_namespaces = [
  { binding = "BLOCKCHAIN_STORAGE", id = "your-kv-id-will-go-here", preview_id = "your-preview-kv-id-will-go-here" }
]
